openapi: 3.0.3
info:
  title: Uføretrygd - Er ung ufør
  description: |-
    Tjeneste for å hente ut om en person var innvilget ung uføre på en bestemt dato.

    Tjenesten krever et token utstedt av Maskinporten med scope `nav:uforetrygd:erungufor.read`.
  version: 1.0.0
servers:
  - url: https://pensjon-gw.ekstern.dev.nav.no/uforetrygd
paths:
  /erungufor:
    post:
      summary: Utfører en spørring for å sjekke om en person er ung ufør
      description: ''
      operationId: erungufor
      security:
        - maskinporten: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErUngUforRequest'
        required: true
      responses:
        200:
          description: Vellykket operasjon
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErUngUforResponse'
        400:
          description: Feil i request-data fra klient
        401:
          description: Autentisering feilet, f.eks manglende token, feil token, utløpt token
        403:
          description: Ikke tilgang til tjenesten, feks feil scope i token
components:
  schemas:
    ErUngUforRequest:
      type: object
      properties:
        fnr:
          type: string
          description: Fødselsnummer, 11 siffer
          example: "01234567890"
        dato:
          type: string
          format: date
          example: "2024-01-01"
    ErUngUforResponse:
      type: object
      properties:
        erUngUfor:
          type: boolean
          example: "true"
        datoIverksatt:
          format: date
          example: "2023-06-01"
        padding:
          type: string
          description: Padding for å sørge for at http svarhodet 'Content-Length' ikke røper om svaret var true eller false. Feltet skal ignoreres av konsumenter av tjenesten
          example: "*****"
  securitySchemes:
    maskinporten:
      type: http
      scheme: bearer
      bearerFormat: JWT
