openapi: 3.0.1
info:
  title: Uføretrygd Lånekassen API
  description: |
    API for å hente informasjon om en brukers uføretrygd som Lånekassen benytter for å vurdere sletting av gjeld.
  version: 1.0.0
servers:
  - url: https://pensjon-q2-gw.ekstern.dev.nav.no/uforetrygd/lanekassen
  - url: https://pensjon-gw.nav.no/uforetrygd/lanekassen
paths:
  /sak:
    post:
      description: |
        Gir nødvendig informasjon til Lånekassen ifbm søknad om sletting av gjeld.
        
        - Krever token fra maskinporten med scope **nav:uforetrygd/lanekassen/slettgjeld.read**
      operationId: sak
      parameters:
        - in: header
          name: x-request-id
          description: UUID for å spore kallet
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SakRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SakResponse'
        400:
          description: Feil i request-data fra klient.
        401:
          description: Autentisering feilet.
        403:
          description: Autorisering til ressurs feilet, feks feil scope i token.
        404:
          description: Fant ingen sak for angitt personId og dato.
  /barnetillegg:
    post:
      description: |
        Gir nødvendig informasjon til Lånekassen ifbm etterkontroll av gjeldssletting.
        
        - Krever token fra maskinporten med scope **nav:uforetrygd/lanekassen/slettgjeld.read**
      operationId: barnetillegg
      parameters:
        - in: header
          name: x-request-id
          description: UUID for å spore kallet
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BarnetilleggRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BarnetilleggResponse'
        400:
          description: Feil i request-data fra klient.
        401:
          description: Autentisering feilet.
        403:
          description: Autorisering til ressurs feilet, feks feil scope i token.
        404:
          description: Fant ingen sak for angitt personId og årstall.
components:
  schemas:
    SakRequest:
      title: Sak - request
      type: object
      properties:
        personId:
          type: string
          description: Fødselsnummer, 11 siffer.
          example: "01234567890"
        dato:
          type: string
          format: YYYY-mm-DD
          description: Støtter kun datoer fra og med 2015-01-01
          example: "2025-01-01"
    SakResponse:
      title: Sak - response
      type: object
      properties:
        harUforetrygdUtbetalt:
          type: boolean
          example: true
          description: Har bruker uføretrygd utbetalt på angitt dato.
        uforegrad:
          type: number
          description: Uføregrad i prosent på angitt dato.
          example: 100
        harBarnetillegg:
          type: boolean
          example: false
          description: Har barnetillegg på angitt dato.
        statusBeregning:
          $ref: '#/components/schemas/StatusBeregning'
    StatusBeregning:
      type: string
      description: |
        ENDELIG - Der er foretatt en endelig beregning på saken.
        FORELOPIG - Det er foretatt en foreløpig beregning på saken, og at det kan komme endringer i fremtiden.
        USIKKER - Datagrunnlaget er manglende for å kunne si om det er en endelig eller foreløpig beregning på saken.
      enum:
        - FORELOPIG
        - ENDELIG
        - USIKKER
      example: ENDELIG
    BarnetilleggRequest:
      title: Barnetillegg - request
      type: object
      properties:
        personId:
          type: string
          description: Fødselsnummer, 11 siffer.
          example: "01234567890"
        arstall:
          type: integer
          description: Støtter kun årstall fra og med 2015
          example: 2025
    BarnetilleggResponse:
      title: Barnetillegg - response
      type: object
      properties:
        utbetaltBarnetillegg:
          type: integer
          description: Netto utbetalt barnetillegg for angitt år
          example: 5000
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT