openapi: 3.0.1
info:
  version: 1.0.1
  title: Pensjon Simuler Alderspensjon
  description: |-
    For å kunne bruke tjenesten må scope i autentiseringen mot Maskinporten settes til `nav:pensjon/v3/alderspensjon`. 
    Dette er en simuleringstjeneste for tjenestepensjonsordninger i offentlig sektor, og benyttes for å kunne simulere
    alderspensjon fra folketrygden for brukere med TP-forhold.
    
  contact: {}
servers:
  - url: https://pensjon-gw.ekstern.dev.nav.no
  - url: https://pensjon-q1-gw.ekstern.dev.nav.no
  - url: https://pensjon-gw.nav.no
paths:
  /simuler/alderspensjon/v3:
    post:
      description: Simulering av alderspensjon
      tags:
        - Simuler alderspensjon
      operationId: ApiSimulerAlderspensjonV3Post
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulerAlderspensjonRequestV3'
      parameters:
        - name: Authorization
          in: header
          description: Format - byte. Standard Authorization header som inneholder et Base64-kodet Bearer-token (JWT-aksesstoken) utstedt av Maskinporten (Difi). Verdien må starte med "Bearer ", deretter følger tokenstrengen.
          required: true
          schema:
              type: string
        - name: tp-nr
          in: header
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
        - name: hentFullAPListe
          in: header
          description: true/false verdi som styrer om listen med AlderspensjonFraFolketrygden skal inneholde alle perioder eller bare for første uttaksdato/hel uttaksdato
          required: false
          schema:
            type: string
            default: false
      responses:
        '200':
          description: The response object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulerAlderspensjonResponseV3'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/responses/IkkelopendeYtelse'
                  - $ref: '#/components/responses/FodtFor1943'
                  - $ref: '#/components/responses/GammeltRegelverk'
                  - $ref: '#/components/responses/LavtTidligUttak'
                  - $ref: '#/components/responses/KortTrygdetid'
                  - $ref: '#/components/responses/SimuleringsGrunnlag'
                  - $ref: '#/components/responses/Annet'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
components:
  responses:
    IkkelopendeYtelse:
      description: Bruker har ikke løpende alderspensjon
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    FodtFor1943:
      description: Bruker er født før 1943.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    GammeltRegelverk:
      description: Bruker har løpende alderspensjon på gammelt regelverk.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    LavtTidligUttak:
      description: Avslag på vilkårsprøving grunnet for lavt tidlig uttak.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    KortTrygdetid:
      description: Avslag på vilkårsprøving grunnet for kort trygdetid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    SimuleringsGrunnlag:
      description: Det ble funnet feil i simuleringsgrunnlaget
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Annet:
      description: Annet
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Garantipensjonsniva:
      title: Garantipensjonsnivå
      type: object
      properties:
        belop:
          type: number
          format: double
        sats:
          type: number
          format: double
        satsType:
          type: string
        tt_anv:
          type: integer
          format: int32
    PensjonsbeholdningPeriode:
      title: PensjonsbeholdningPeriode
      type: object
      properties:
        pensjonsbeholdning:
          type: number
          format: double
        garantipensjonsbeholdning:
          type: number
          format: double
        garantitilleggsbeholdning:
          type: number
          format: double
        datoFom:
          type: string
        garantipensjonsniva:
          type: object
          items:
            $ref: '#/components/schemas/Garantipensjonsniva'
    Pensjonsperiode:
      title: Pensjonsperiode
      type: object
      properties:
        arligUtbetaling:
          type: integer
          format: int32
        datoFom:
          type: string
    AlderspensjonFraFolketrygden:
      title: AlderspensjonFraFolketrygden
      type: object
      properties:
        datoFom:
          type: string
        delytelser:
          type: array
          items:
            $ref: '#/components/schemas/Delytelse'
        uttaksgrad:
          type: integer
          format: int32
    Simuleringsdata:
      title: Simuleringsdata
      type: object
      properties:
        poengArTom1991:
          type: integer
          format: int32
        poengArFom1992:
          type: integer
          format: int32
        sluttpoengtall:
          type: number
          format: double
        anvendtTrygdetid:
          type: integer
          format: int32
        basisgp:
          type: number
          format: double
        basistp:
          type: number
          format: double
        basispt:
          type: number
          format: double
        forholdstallUttak:
          type: number
          format: double
        delingstallUttak:
          type: number
          format: double
        skjermingstillegg:
          type: number
          format: double
        uforegradVedOmregning:
          type: integer
          format: int32
        datofom:
          type: string
    SimulertAP:
      title: SimulertAP
      type: object
      properties:
        simuleringsdataListe:
          type: array
          items:
            $ref: '#/components/schemas/Simuleringsdata'
    Delytelse:
      title: Delytelse
      type: object
      properties:
        pensjonstype:
          type: string
        belop:
          type: integer
          format: int32
    SimulerAlderspensjonResponseV3:
      title: SimulerAlderspensjonResponseV3
      type: object
      properties:
        pensjonsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Pensjonsperiode'
        simuleringsdataliste:
          type: array
          items:
            $ref: '#/components/schemas/Simuleringsdata'
        pensjonsbeholdningsperioder:
          type: array
          items:
            $ref: '#/components/schemas/PensjonsbeholdningPeriode'
        alderspensjonFraFolketrygden:
          type: array
          items:
            $ref: '#/components/schemas/AlderspensjonFraFolketrygden'
        harUttak:
          type: boolean
        harTidligereUttak:
          type: boolean
        afpPrivatBeholdningVedUttak:
          type: integer
          format: int32
        sisteGyldigeOpptjeningsAr:
          type: integer
          format: int32
    SimulerAlderspensjonRequestV3:
      title: SimulerAlderspensjonRequestV3
      type: object
      properties:
        fnr:
          type: string
        forsteUttak:
          $ref: '#/components/schemas/UttaksperiodeV3'
        heltUttak:
          $ref: '#/components/schemas/UttaksperiodeV3'
        arIUtlandetEtter16:
          type: integer
          description: Settes for å kunne redusere trygdetid ved simulering.
          format: int32
        sivilstandVedPensjonering:
          $ref: '#/components/schemas/SivilstandVedPensjonering'
        epsPensjon:
          type: boolean
          description: Angir om ektefelle/partner/samboer mottar pensjon.
        eps2G:
          type: boolean
          description: Angir om ektefelle/partner/samboer har inntekt over 2G
        fremtidigInntektListe:
          type: array
          items:
            $ref: '#/components/schemas/FremtidigInntekt'
        simulerMedAfpPrivat:
          type: boolean
          description: 'Angir '
    UttaksperiodeV3:
      title: UttaksperiodeV3
      description: Dette er Uttaksperioden. Angir gradering for uttaksperioden.
      type: object
      properties:
        datoFom:
          type: string
          format: date-time
        grad:
          type: integer
          format: int32
    FremtidigInntekt:
      title: FremtidigInntekt
      type: object
      description: Angir inntekt som benyttes som opptjeningsgrunnlag for perioden frem til neste angitte inntekt(fomdato), eller bruker når maks opptjeningsalder. Inntekter for år der bruker har blitt godskrevet opptjening fra skatteoppgjøret ignoreres. Siste gyldige opptjeningsår i responsen angir hvilket år dette gjelder.
      properties:
        arligInntekt:
          type: integer
          format: int32
        fomDato:
          type: string
          format: date-time
    SivilstandVedPensjonering:
      title: SivilstandVedPensjonering
      example: ENKE
      type: string
      enum:
        - ENKE
        - GIFT
        - GJES
        - GJPA
        - GJSA
        - GLAD
        - PLAD
        - REPA
        - SAMB
        - SEPA
        - SEPR
        - SKIL
        - SKPA
        - UGIF
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Simuler alderspensjon
    description: ''
