openapi: 3.0.1
info:
  title: AFP Beholdningsgrunnlag
  description: Tjenester for beregning og simulering av AFP beholdningsgrunnlag.
  version: 1.0.0
servers:
  - url: https://template.value/template/value
paths:
  /opptjening/afp/beholdningsgrunnlag/beregn:
    post:
      description: Beregner AFP beholdningsgrunnlag for angitt personId fra og med angitt dato.
      operationId: beregn
      parameters:
        - in: header
          name: x-request-id
          description: UUID for å spore kallet
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BeregnRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        400:
          description: Feil i request-data fra klient
        401:
          description: Autentisering feilet
        403:
          description: Autorisering til ressurs feilet, feks feil scope i token
  /opptjening/afp/beholdningsgrunnlag/simuler:
    post:
      description: Simulerer beholdningsgrunnlag med tilvekst fra oppgitte inntekter fra og med angitt dato. NB! Grunnlag med fraOgMedDato senere enn siste kjente grunnbeløpsendring vil ikke være lønnsvekstregulert - se https://www.nav.no/grunnbelopet
      operationId: simuler
      parameters:
        - in: header
          name: x-request-id
          description: UUID for å spore kallet
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulerRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        400:
          description: Feil i request-data fra klient
        401:
          description: Autentisering feilet
        403:
          description: Autorisering til ressurs feilet, feks feil scope i token
components:
  schemas:
    BeregnRequest:
      type: object
      properties:
        personId:
          type: string
          description: Fødselsnummer, 11 siffer
          example: "01234567890"
        fraOgMedDato:
          description: Angir datoen man ønsker beholdningsgrunnlag fra og med. Response inkluderer alle beholdningsgrunnlag på angitt dato og senere.
          type: string
          format: YYYY-mm-DD
          example: "2024-01-01"
    SimulerRequest:
      type: object
      properties:
        personId:
          type: string
          description: Fødselsnummer, 11 siffer
          example: "01234567890"
        fraOgMedDato:
          description: Angir datoen man ønsker beholdningsgrunnlag fra og med. Response inkluderer alle beholdningsgrunnlag på angitt dato og senere.
          type: string
          format: YYYY-mm-DD
          example: "2024-01-01"
        fremtidigInntektListe:
          type: array
          items:
            $ref: '#/components/schemas/FremtidigInntekt'
    FremtidigInntekt:
      type: object
      properties:
        fraOgMedDato:
          description: Måneden den årlige inntekten gjelder fra - gyldig frem til neste inntekt med senere fraOgMedDato, eller til "evig" tid dersom ingen eksisterer. Årlig inntekt regnes om til månedsinntekt og multipliseres med antall måneder per år - eks (fraOgMedDato:2024-01-01, inntekt:100.000) + (fraOgMedDato:2024-07-01, inntekt:200.000) -> (100.000/12x6) + (200.000/12x6) -> (50.000) + (100.000) = 150.000 for året 2024.
          type: string
          example: "2024-01-01"
        arligInntekt:
          type: integer
          example: 100000
    Response:
      type: object
      description: AFP beholdningsgrunnlag gjeldende på angitt fraOgMedDato og senere.
      properties:
        afpBeholdningsgrunnlag:
          type: array
          items:
            $ref: '#/components/schemas/AFPBeholdningsgrunnlag'
    AFPBeholdningsgrunnlag:
      type: object
      properties:
        fraOgMedDato:
          description: Datoen beholdningsgrunnlaget er gjeldende fra - gyldig frem til neste grunnlag med senere fraOgMedDato, eller til "evig" tid dersom ingen eksisterer.
          type: string
          format: YYYY-mm-DD
          example: "2024-01-01"
        belop:
          description: Belop per fraOgMedDato
          type: number
          example: 123456
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
