openapi: 3.0.1
info:
  title: Pensjon TP-registeret, forhold mellom person og ordning, og Innsyn.
  description: |-
    API for å behandle forhold mellom person og ordning for eksterne samhandlere,
    og innsyn i registrerte tjenestepensjonsforhold og ytelser.

    For å kunne bruke tjenesten må scope i autentiseringen mot Maskinporten settes til: `nav:pensjon/v1/tpregisteret`
    
    Opprettelse av ytelse av type `UFORE` eller `GJENLEVENDE` vil det ikke returneres vedtakopplysninger.
    Dette må hentes med hentSamordningsdata (SOAP)
  contact: {}
  version: '1.0'
servers:
  - url: https://pensjon-q1-gw.ekstern.dev.nav.no/tjenestepensjon/q1
  - url: https://pensjon-gw.ekstern.dev.nav.no/tjenestepensjon
  - url: https://pensjon-gw.nav.no/tjenestepensjon
security:
  - Maskinporten:
    - nav:pensjon/v1/tpregisteret

paths:
  /forhold/forholdListe/get:
    get:
      tags:
        - Person
      summary: Forholdsliste
      description: Henter ut liste av forhold. Forhold(ene) inkluderer liste av registrerte ytelser. <br>
        Hvis ordningen har et forhold på person så vil endepunktet svare med en liste av alle forhold på personen.<br> 
        Hvis ordningen ikke har et forhold på person så vil endepunktet svare 403, for da har ikke ordningen tilgang til personen.
      operationId: ForholdlisteGet
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/samhandlerPersonDto'
        '401':
          description: Ugyldig access token
        '403':
          description: Ikke tilgang til person eller feil scope på token fra Maskinporten
      deprecated: false
  /forhold/{ordning}/get:
    get:
      tags:
        - Forhold
      summary: Hent et forhold
      description: Hent et forhold på  eksisterende ordning for person.
      operationId: HentForholdGet
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: ordning
          in: path
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/samhandlerForhold'
        '401':
          description: Ugyldig access token
        '403':
          description: Ikke tilgang til ordning eller feil scope på token fra Maskinporten
        '404':
          description: Person eller Ordning ikke funnet
      deprecated: false
  /forhold/{ordning}/put:
    put:
      tags:
        - Forhold
      summary: Opprett et forhold.
      description: Opprett et forhold på eksisterende ordning for person.
      operationId: OpprettForholdPut
      requestBody:
        required: true
        description: Et forhold
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/samhandlerForhold'
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: ordning
          in: path
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/samhandlerForhold'
        '401':
          description: Ugyldig access token
        '403':
          description: Ikke tilgang til ordning eller feil scope på token fra Maskinporten
        '404':
          description: Person eller Ordning ikke funnet
      deprecated: false
  /forhold/{ordning}/delete:
    delete:
      tags:
        - Forhold
      summary: Slett et forhold.
      description: Slett et forhold på eksisterende ordning for person.
      operationId: SlettForholdDelete
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: ordning
          in: path
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '401':
          description: Ugyldig access token
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
        '403':
          description: Ikke tilgang til ordning eller feil scope på token fra Maskinporten.
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
        '404':
          description: Person eller forhold ikke funnet
      deprecated: false
  /forhold/{ordning}/datoSistOpptjening/update:
    patch:
      tags:
        - Forhold
      summary: Opprette dato for sist opptjening på forhold
      description: Opprette dato for sist opptjening på forhold for en person i en ordning.
      operationId: OpprettDatoSistOpptjeningPatch
      requestBody:
        description: dato for siste opptjening(oppgis i "", eksempelvis "2023-01-01")
        content:
          application/json:
            schema:
              type: string
              format: date
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: ordning
          in: path
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/samhandlerPerson'
        '401':
          description: Ugyldig access token
        '403':
          description: Ikke tilgang til ordning eller feil scope på token fra Maskinporten
        '404':
          description: Person eller forhold ikke funnet
      deprecated: false
  /forhold/{ordning}/datoSistOpptjening/delete:
    delete:
      tags:
        - Forhold
      summary: Slette dato for sist opptjening på forhold
      description: Slette dato for sist opptjening på forhold for en person i en ordning.
      operationId: SlettDatoSistOpptjeningDelete
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: ordning
          in: path
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/samhandlerPerson'
        '401':
          description: Ugyldig access token
        '403':
          description: Ikke tilgang til ordning eller feil scope på token fra Maskinporten
        '404':
          description: Person eller forhold ikke funnet
      deprecated: false
  /forhold/{ordning}/ytelse/post:
    post:
      tags:
        - Ytelse
      summary: Opprett en ytelse.
      description: Opprett en ytelse på eksisterende forhold.
      operationId: opprettYtelsePost
      requestBody:
        description: En ytelse
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/samhandlerYtelse'
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: ordning
          in: path
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/samhandlerYtelse'
        '401':
          description: Ugyldig access token
        '403':
          description: Ikke tilgang til ordning eller feil scope på token fra Maskinporten
        '404':
          description: Person eller forhold ikke funnet
        '409':
          description: Identisk ytelse eksisterer allerede
      deprecated: false
  /forhold/{ordning}/ytelse/{ytelseid}/delete:
    delete:
      tags:
        - Ytelse
      summary: Slette en ytelse.
      description: Slette en ytelse på eksisterende forhold.
      operationId: slettYtelseDelete
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: ordning
          in: path
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
        - name: ytelseId
          in: path
          description: Unik id for ytelse
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '401':
          description: Ugyldig access token
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
        '403':
          description: Ikke tilgang til ordning eller feil scope på token fra Maskinporten.
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
        '404':
          description: Person, forhold eller ytelse ikke funnet
      deprecated: false
  /forhold/{ordning}/ytelse/{ytelseid}/put:
    put:
      tags:
        - Ytelse
      summary: Endre en ytelse.
      description: Endre en ytelse på eksisterende forhold.
      operationId: endreYtelsePut
      requestBody:
        description: En ytelse
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/samhandlerYtelse'
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: ordning
          in: path
          description: Tjenestepensjonsnummer
          required: true
          schema:
            type: string
        - name: ytelseid
          in: path
          description: YtelseId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/samhandlerYtelse'
        '401':
          description: Ugyldig access token
        '403':
          description: Ikke tilgang til ordning eller feil scope på token fra Maskinporten
        '404':
          description: Person, Ytelse eller forhold ikke funnet
      deprecated: false
  /innsyn/forhold/{tpNr}/get:
    get:
      tags:
        - Deprecated
      summary: Innsyn, forhold og ytelser
      description: Henter ut forhold med ytelser for ett gitt fnr og tjenestepensjonsnummer.
      operationId: InnsynForholdGet
      parameters:
        - name: fnr
          in: header
          description: Person identifikator
          required: true
          schema:
            type: string
        - name: tpNr
          in: path
          description: Tjenestepensjons nummer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/innsynForhold'
        '401':
          description: Ugyldig access token
        '403':
          description: Ikke tilgang til forhold eller feil scope på token fra Maskinporten
        '404':
          description: Person eller forhold ikke funnet
      deprecated: true
components:
  schemas:
    samhandlerPerson:
      title: Person med forhold og ytelser
      type: object
      required:
        - fnr
      properties:
        fnr:
          type: string
          description: personidentifikator
        forhold:
          type: array
          description: Liste av forhold tilhørende person, med liste av ytelser
          items:
            $ref: '#/components/schemas/samhandlerForhold'
    samhandlerForhold:
      title: Forhold med ytelser
      type: object
      required:
        - tpNr
      properties:
        kilde:
          type: string
          description: KildeTypeCode (TPLEV, PP01, )
        tpNr:
          type: string
          description: Tjenestepensjonsnummer
        tpOrdningNavn:
          type: string
          readOnly: true
          description: Navn på tjenestepensjonsordning.
        datoSistOpptjening:
          type: string
          readOnly: true
          description: dato for sist opptjening i forhold.
          format: date
        sistEndretDatoSistOpptjening:
          type: string
          readOnly: true
          description: Timestamp for endring av datoSistOpptjening.
          format: date-time
        changeStamp:
          type: object
          readOnly: true
          description: Hvem opprettet og endret med datoer.
          items:
            $ref: '#/components/schemas/changeStampDateDto'
        ytelser:
          type: array
          readOnly: true
          description: Liste av ytelser tilhørende forhold
          items:
            $ref: '#/components/schemas/samhandlerYtelse'
        harGjenlevendeYtelse:
          type: boolean
          readOnly: true
          description: Hvorvidt vedkommende har gjenlevendeYtelse eller ikke. Deprecated - Vennligst benytt ytelse.type
          deprecated: true
          nullable: true
    samhandlerPersonDto:
      title: Person med forhold og ytelser
      type: object
      properties:
        fNr:
          type: string
          description: personidentifikator
        forhold:
          type: array
          description: Liste av forhold tilhørende person
          items:
            $ref: '#/components/schemas/samhandlerForhold'
    changeStampDateDto:
      title: ChangeStampDateDto
      type: object
      properties:
        createdBy:
          type: string
          description: Navn på person som opprettet forhold
        createdDate:
          type: string
          description: Dato opprettet
          format: date
        updatedBy:
          type: string
          description: Navn på person som oppdaterte forhold
        updatedDate:
          type: string
          description: Dato endret
          format: date
    samhandlerYtelse:
      title: Ytelse
      type: object
      required:
        - ytelseType
        - datoYtelseIverksattFom
      properties:
        ytelseType:
          type: string
          enum:
            - ALDER
            - UFORE
            - GJENLEVENDE
            - BARN
            - AFP
            - OPPSATT_BTO_PEN
            - SAERALDER
            - PAASLAGSPENSJON
            - OVERGANGSTILLEGG
            - BETINGET_TP
            - LIVSVARIG_AFP
          description: YtelseType
        datoInnmeldtYtelseFom:
          type: string
          description: Dato da ytelse ble innmeldt
          format: date
        datoYtelseIverksattFom:
          type: string
          description: Dato da ytelse ble iverksatt
          format: date
        datoYtelseIverksattTom:
          type: string
          description: Dato da iverksatt ytelse avsluttet
          format: date
        changeStamp:
          type: object
          description: Hvem opprettet og endret med datoer.
          readOnly: true
          items:
            $ref: '#/components/schemas/changeStampDateDto'
        ytelseId:
          type: integer
          description: Unik Id for ytelse, av format long.
          format: int64
          readOnly: true
    innsynForhold:
      title: InnsynForhold
      type: object
      properties:
        tpNr:
          type: string
          description: Tjenestepensjonsnummeret som forholdet tilhører
        datoSistOpptjening:
          type: string
          description: Dato siste opptjening for forhold.
          format: date
        sistEndretdatoSistOpptjening:
          type: string
          description: Timestamp for endring av datoSistOpptjening.
          format: date-time
        ytelser:
          type: array
          description: Liste med ytelser som tilhører dette forholdet
          items:
            $ref: '#/components/schemas/innsynYtelse'
    innsynYtelse:
      title: InnsynYtelse
      type: object
      properties:
        type:
          type: string
          description: Ytelsestype (ALDER, UFORE, mm)
        medlemskapDatoFom:
          type: string
          description: Dato da medlemskapet startet
          format: date
        datoFom:
          type: string
          description: Fra og med dato
          format: date
        datoTom:
          type: string
          description: Til og med dato
          format: date
  securitySchemes:
    Maskinporten:
      type: http
      description: "Bearer token utstedt av Maskinporten."
      scheme: Bearer
      in: header
