openapi: 3.0.1
info:
  title: Pensjon AFP-privat
  description: Inneholder tjenester for å behandle og hente informasjon om en AFP-privat saker/brukere.
    søknad.
  version: 1.0.0
servers:
  - url: https://template.value/template/value
paths:
  /mottarAfpPrivat:
    post:
      description: Hent ut informasjon om bruker mottar AFP-privat.
      operationId: mottarafpprivat
      parameters:
        - in: header
          name: x-request-id
          description: UUID for å spore kallet
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MottarAfpPrivatRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MottarAfpPrivatResponse'
        400:
          description: Feil i request-data fra klient
        401:
          description: Autentisering feilet
        403:
          description: Autorisering til ressurs feilet, feks feil scope i token		  
components:
  schemas:
    MottarAfpPrivatRequest:
      title: Mottar AFP Privat - request
      type: object
      properties:
        personId:
          type: string
          description: Fødselsnummer, 11 siffer
          example: "01234567890"
        fraOgMedDato:
          type: string
          format: YYYY-mm-DD
          description: Ønsket virkningstidspunkt å sjekke på om bruker mottar afp-privat          
          example: "2024-01-01"          
    MottarAfpPrivatResponse:
      title: Mottar AFP Privat - response
      type: object
      properties:
        mottarAfpPrivat:
          type: boolean
  securitySchemes:
    Ocp-Apim-Subscription-Key:
      type: apiKey
      description: ""
      name: Ocp-Apim-Subscription-Key
      in: header
