openapi: 3.0.1
info:
  title: Pensjon AFP-privat
  description: Inneholder tjenester for å behandle og hente informasjon om en AFP-privat saker/brukere.
  version: 1.0.0
servers:
  - url: https://pensjon-gw.ekstern.dev.nav.no/pensjon/afp-privat/
  - url: https://pensjon-gw.nav.no/pensjon/afp-privat/
paths:
  /mottarAfpPrivat:
    post:
      description: Hent ut informasjon om bruker mottar AFP-privat fra og med gitt tidspunkt. Scope mot Maskinporten settes til `nav:pensjon/afpprivat/mottarafpprivat`.
      operationId: mottarafpprivat
      parameters:
        - in: header
          name: x-request-id
          description: UUID for å spore kallet
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MottarAfpPrivatRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MottarAfpPrivatResponse'
        400:
          description: Feil i request-data fra klient
        401:
          description: Autentisering feilet
        403:
          description: Autorisering til ressurs feilet, feks feil scope i token
  /mottar-eller-har-mottatt-afpprivat:
    post:
      description: Hent ut informasjon om bruker mottar eller har mottatt AFP-privat. Scope mot Maskinporten settes til `nav:pensjon/afpprivat/mottarellerharmottattafpprivat`.
      operationId: mottarellerharmottattafpprivat
      parameters:
        - in: header
          name: x-request-id
          description: UUID for å spore kallet
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MottarEllerHarMottattAfpPrivatRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MottarEllerHarMottattAfpPrivatResponse'
        400:
          description: Feil i request-data fra klient
        401:
          description: Autentisering feilet
        403:
          description: Autorisering til ressurs feilet, feks feil scope i token

components:
  schemas:
    MottarAfpPrivatRequest:
      title: Mottar AFP Privat - request
      type: object
      properties:
        personId:
          type: string
          description: Fødselsnummer, 11 siffer
          example: "01234567890"
        fraOgMedDato:
          type: string
          format: YYYY-mm-DD
          description: Ønsket virkningstidspunkt å sjekke på om bruker mottar afp-privat          
          example: "2024-01-01"          
    MottarAfpPrivatResponse:
      title: Mottar AFP Privat - response
      type: object
      properties:
        mottarAfpPrivat:
          type: boolean
    MottarEllerHarMottattAfpPrivatRequest:
      title: Mottar eller har mottatt AFP Privat - request
      type: object
      properties:
        personId:
          type: string
          description: Fødselsnummer, 11 siffer
          example: "01234567890"
    MottarEllerHarMottattAfpPrivatResponse:
      title: Mottar eller har mottatt AFP Privat - response
      type: object
      properties:
        mottarEllerHarMottattAfpPrivat:
          type: boolean
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    security:
      - bearerAuth: [ ]
