openapi: 3.0.1
info:
  title: Pensjon Samordningspliktige hendelser.
  description: |-
    Hendelseskø for samordningspliktige hendelser (AP, AFP, OMS).

    Påkrevd scope-verdi: `nav:pensjon/v1/samordning`
  contact: {}
  version: '1.0'
servers:
  - url: https://pensjon-gw.ekstern.dev.nav.no/samordning
  - url: https://pensjon-gw.nav.no/samordning
security:
  - Maskinporten: []
paths:
  /hendelser:
    get:
      summary: Les samordningspliktige hendelser.
      description: "Endepunktet returnerer en feed som inneholder hendelser tilhørende et angitt tjenestepensjonsnummer.
                    \n\nFeeden benytter paginering, som deler opp feeden i sider basert på angitt antall hendelser per side. Hver side inneholder en liste med _hendelser_, samt en _nextUrl_ som peker til neste side av feeden. Siste side er nådd når _nextUrl_ er _null_.
                    \n\nSekvensnummer kan benyttes som offset for feeden. Hendelser knyttet til et tjenestepensjonsnummer starter med sekvensnummer 1 til og med _sisteSekvensnummer_."
      operationId: HendelserGet
      parameters:
        - name: tpnr
          in: query
          description: Id for ordning som vedtaket tilhører
          required: true
          schema:
            type: string
        - name: side
          in: query
          description: Sidenummer for paginert søk.
          required: false
          schema:
            type: integer
            default: 0
        - name: antall
          in: query
          description: Antall hendelser per side.
          required: false
          schema:
            type: number
            format: int64
            default: 10000
        - name: sekvensnummer
          in: query
          description: Start innlesningen fra dette sekvensnummeret
          required: false
          schema:
            type: number
            format: int64
            default: 1
        - name: Authorization
          in: header
          description: 'Standard Authorization-header som inneholder et Base64-kodet Bearer-token (JWT-aksesstoken) utstedt av Maskinporten (Difi). Verdien må starte med "Bearer ", deretter følger tokenstrengen.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/feed'
        '401':
          description: Ugyldig access token
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
        '500':
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
      deprecated: false
components:
  schemas:
    feed:
      title: Feed
      type: object
      properties:
        hendelser:
          type: array
          description: Liste av hendelser
          items:
            $ref: '#/components/schemas/hendelse'
        sisteSekvensnummer:
          type: string
          description: Siste sekvensnummer fra forrige side
          format: long
        sisteLesteSekvensnummer:
          type: string
          description: Det nyeste sekvensnummeret
          format: long
        nextUrl:
          type: string
          description: Lenke til neste side
    hendelse:
      title: Hendelse
      type: object
      description: En hendelse tilknyttet samordningspliktig ytelse
      properties:
        ytelsesType:
          type: string
          description: Samordningspliktig ytelse knyttet til hendelse
        identifikator:
          type: string
          description: Identifiserer brukeren (eks. fnr/dnr)
        vedtakId:
          type: string
          description: Identifiserer vedtak i fagsystemet(Pesys, Gjenny)
        samId:
          type: string
          description: Samordning-id tilknyttet vedtaket.
        fom:
          type: string
          description: Dato fra og med.
          format: date
        tom:
          type: string
          description: Dato til og med.
          format: date
  securitySchemes:
    Maskinporten:
      type: http
      description: "Bearer token utstedt av Maskinporten."
      scheme: Bearer
      in: header